name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build -x lint -x testDebugUnitTest -x testReleaseUnitTest
        
    - name: Run unit tests
      run: |
        ./gradlew testDebugUnitTest
        
    - name: Run instrumented tests on Firebase Test Lab
      uses: asadmansr/Firebase-Test-Lab-Action@v1.0.2
      with:
        serviceAccountJson: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        device: model=redfin,version=30,locale=en,orientation=portrait
        testApkPath: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/reports/
        retention-days: 5



