name: Android CI/CD + Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      # --- 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- 2) Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # --- 3) Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # --- 4) Build project for CodeQL & APK
      - name: Build project
        run: ./gradlew clean assembleDebug assembleRelease --stacktrace

      # --- 5) Run CodeQL analysis
      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: "security-and-quality"

      # --- 6) Upload APKs as artifacts
      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk

      # --- 7) Create GitHub Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1-${{ github.run_number }}
          name: APK Release ${{ github.run_number }}
          body: Automated release of APKs from CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- 8) Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
